import os
import subprocess
import tempfile
from typing import Dict, Set
from pathlib import Path


class GraphVisualizer:
    def __init__(self):
        self.d2_available = self._check_d2_installation()
    
    def _check_d2_installation(self) -> bool:
        """Проверяет, установлен ли D2."""
        try:
            result = subprocess.run(["d2", "--version"], capture_output=True, text=True)
            return result.returncode == 0
        except:
            return False
    
    def generate_d2_code(self, graph: Dict[str, Set[str]], root_package: str = "") -> str:
        """
        Генерирует код на языке D2 из графа зависимостей.
        """
        lines = []
        lines.append("# Dependency Graph generated by depvis")
        lines.append("")
        
        # Создаем все узлы
        all_nodes = set()
        for package, deps in graph.items():
            all_nodes.add(package)
            all_nodes.update(deps)
        
        # Добавляем связи
        for package, dependencies in sorted(graph.items()):
            for dep in sorted(dependencies):
                lines.append(f"{package} -> {dep}")
        
        # Выделяем корневой пакет
        if root_package and root_package in all_nodes:
            lines.append("")
            lines.append(f"{root_package}.style: {{")
            lines.append("  stroke: #2563eb")
            lines.append("  stroke-width: 3")
            lines.append("  fill: #dbeafe")
            lines.append("}")
        
        return "\n".join(lines)
    
    def save_d2_to_file(self, d2_code: str, filename: str = "graph.d2") -> str:
        """
        Сохраняет D2 код в файл.
        """
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(d2_code)
        return filename
    
    def generate_png_from_d2(self, d2_filename: str, output_filename: str = "graph.png") -> bool:
        """
        Генерирует PNG из D2 файла.
        """
        if not self.d2_available:
            print("D2 is not installed. Please install D2 from https://d2lang.com/")
            return False
        
        try:
            result = subprocess.run([
                "d2", 
                d2_filename, 
                output_filename,
                "--layout", "dagre",
                "--theme", "1"
            ], capture_output=True, text=True)
            
            if result.returncode == 0:
                print(f"PNG generated successfully: {output_filename}")
                return True
            else:
                print(f"D2 generation failed: {result.stderr}")
                return False
                
        except Exception as e:
            print(f"Error generating PNG: {e}")
            return False
    
    def visualize_graph(self, graph: Dict[str, Set[str]], output_file: str = "graph.png", 
                       root_package: str = "") -> bool:
        """
        Основной метод для визуализации графа.
        """
        print(f"\nGenerating visualization: {output_file}")
        
        # Генерируем D2 код
        d2_code = self.generate_d2_code(graph, root_package)
        print("D2 code generated successfully")
        
        # Сохраняем D2 файл
        d2_filename = output_file.replace('.png', '.d2')
        self.save_d2_to_file(d2_code, d2_filename)
        print(f"D2 file saved: {d2_filename}")
        
        # Генерируем PNG
        success = self.generate_png_from_d2(d2_filename, output_file)
        
        if success:
            print(f"Visualization completed: {output_file}")
        else:
            print("Visualization failed - D2 code saved for manual processing")
            print(f"You can manually run: d2 {d2_filename} {output_file}")
        
        return success
    
    def compare_with_npm_visualization(self, package: str):
        """
        Сравнивает с штатными инструментами визуализации npm.
        """
        print(f"\nComparison with NPM visualization tools for {package}:")
        print("1. npm-remote-ls: Provides tree view of dependencies")
        print("2. npm ls: Shows local dependency tree") 
        print("3. Our D2 visualization: Interactive graph with better layout")
        print("\nDifferences:")
        print("- Our tool: Interactive SVG/PNG with graph layout")
        print("- NPM tools: Text-based tree representation")
        print("- Our tool: Shows full dependency graph structure")
        print("- NPM tools: Focus on version resolution")